pipeline:
  agent:
    any:
      - label 'master'  # This runs the pipeline on any available agent labeled 'master'

  stages:
    - stage: Checkout
      steps:
        - script:
            - echo 'Checking out code from GitHub'
            - git checkout https://github.com/rahulpandharkar/Keylogger

    - stage: Execute_Test
      steps:
        - script:
            - echo 'Executing performance test using bzt'
            - bzt execution.yml
