pipeline:
  agent:
    any:
      - label 'master'  # This runs the pipeline on any available agent labeled 'master'

  stages:
    - stage: Checkout
      steps:
        - script:
            - echo 'Checking out code from GitHub'
            - git checkout https://github.com/rahulpandharkar/Keylogger

    - stage: Build
      steps:
        - script:
            - echo 'Building the project'
            - # Add your build commands here

    - stage: Test
      steps:
        - script:
            - echo 'Running tests'
            - # Add your test commands here

    - stage: Deploy
      steps:
        - script:
            - echo 'Deploying the project'
            - # Add your deployment commands here

    - stage: Notify
      steps:
        - script:
            - echo 'Notifying about the build'
            - # Add notification or post-build actions here
